version: "3.8"

# Connect to your existing surge-network where your Bitcoin signet node runs
networks:
  surge-network:
    external: true

services:
  # No bitcoind service needed - using your existing custom signet node
  # No LND services needed - using your existing LND setup

  # Local Loop Server for your custom signet - connects to your existing LND
  loopserver:
    image: lightninglabs/loopserver
    container_name: loopserver-signet
    restart: unless-stopped
    network_mode: host # Use host networking to access your LND and Bitcoin node
    volumes:
      - "loopserver:/root/loopserver"
      # Mount LND credentials from temporary directory
      - "/tmp/lnd-creds:/lnd-creds:ro"
    command:
      - "daemon"
      - "--maxamt=5000000"
      # Connect to your existing LND
      - "--lnd.host=localhost:10009"
      - "--lnd.macaroonpath=/lnd-creds/admin.macaroon"
      - "--lnd.tlspath=/lnd-creds/tls.cert"
      # Connect to your Bitcoin signet node (accessible via host network)
      - "--bitcoin.host=localhost:38332"
      - "--bitcoin.user=bitcoin"
      - "--bitcoin.password=bitcoin"
      - "--bitcoin.zmqpubrawblock=tcp://localhost:28332"
      - "--bitcoin.zmqpubrawtx=tcp://localhost:28333"

  # Loop client connecting directly to local loop server and your existing LND
  loopclient:
    image: loopd
    container_name: loopclient-signet
    build:
      context: ../
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: host # Use host networking to access your LND and loop server
    volumes:
      - "loopclient:/root/.loop"
      # Mount LND credentials from temporary directory
      - "/tmp/lnd-creds:/lnd-creds:ro"
    depends_on:
      - loopserver
    command:
      - "loopd"
      - "--experimental"
      - "--network=signet"
      - "--debuglevel=debug"
      # Allow external access on both RPC and REST
      - "--rpclisten=0.0.0.0:11010"
      - "--restlisten=0.0.0.0:9080"
      # TLS configuration for local development
      - "--tlsdisableautofill"
      # Connect directly to LOCAL loop server (bypass Aperture for simplicity)
      - "--server.host=localhost:11009"
      - "--server.notls"
      # Connect to your existing LND on localhost
      - "--lnd.host=localhost:10009"
      - "--lnd.macaroonpath=/lnd-creds/admin.macaroon"
      - "--lnd.tlspath=/lnd-creds/tls.cert"

volumes:
  loopserver:
  loopclient:
